backend:
  name: git-gateway
  branch: main # Your GitHub default branch

media_folder: "static/img" # Where uploaded images go

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - { name: "title", label: "Title", widget: "string" }
          - { name: "hero_text", label: "Hero Text", widget: "text" }
          - { name: "banner_image", label: "Banner Image", widget: "image" }